# Generated by Django 3.0.4 on 2020-04-21 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AutoInsurance',
            fields=[
                ('insurance_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insurance_status', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'auto_insurance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AutoRecord',
            fields=[
                ('a_r_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auto_record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('marital_status', models.CharField(max_length=1)),
                ('customer_type', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=2)),
                ('street', models.CharField(max_length=30)),
                ('zip', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('license_num', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=30)),
                ('l_name', models.CharField(max_length=30)),
                ('birthdate', models.DateTimeField()),
            ],
            options={
                'db_table': 'driver',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HomeInsurance',
            fields=[
                ('insurance_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insurance_status', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'home_insurance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HomeRecord',
            fields=[
                ('h_r_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'home_record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InsuredHome',
            fields=[
                ('home_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('home_purchase_date', models.DateTimeField()),
                ('home_purchase_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('home_area', models.IntegerField()),
                ('home_type', models.CharField(max_length=1)),
                ('auto_fire_notification', models.IntegerField()),
                ('home_security_system', models.IntegerField()),
                ('swimming_pool', models.CharField(blank=True, max_length=1, null=True)),
                ('basement', models.IntegerField()),
            ],
            options={
                'db_table': 'insured_home',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InsuredVehicle',
            fields=[
                ('vin', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('make_model_year', models.SmallIntegerField()),
                ('vehicle_status', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'insured_vehicle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceAuto',
            fields=[
                ('invoice_id', models.IntegerField(primary_key=True, serialize=False)),
                ('invoice_date', models.DateTimeField()),
                ('payment_due_date', models.DateTimeField()),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'invoice_auto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceHome',
            fields=[
                ('invoice_id', models.IntegerField(primary_key=True, serialize=False)),
                ('invoice_date', models.DateTimeField()),
                ('payment_due_date', models.DateTimeField()),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'invoice_home',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentAuto',
            fields=[
                ('payment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('payment_date', models.DateTimeField()),
                ('payment_method', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'payment_auto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentHome',
            fields=[
                ('payment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('payment_date', models.DateTimeField()),
                ('payment_method', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'payment_home',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleDriver',
            fields=[
                ('v_d_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'vehicle_driver',
                'managed': False,
            },
        ),
    ]
